version: "3.9"

services:
  # Databases
  mongo-auth:
    image: mongo
    ports: ["27017:27017"]

  mongo-crm:
    image: mongo
    ports: ["27018:27017"]

  redis:
    image: redis

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Microservices
  auth-service:
    build: ./auth-service
    ports: ["5001:5001"]
    depends_on: [mongo-auth, redis, kafka]

  crm-service:
    build: ./crm-service
    ports: ["5002:5002"]
    depends_on: [mongo-crm, kafka]

  notification-service:
    build: ./notification-service
    ports: ["5003:5003"]
    depends_on: [kafka]

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports: ["80:80"]
    depends_on:
      - auth-service
      - crm-service
      - notification-service
